sudo: required
language: c
services:
  - docker
script:
  - docker version
  - VERSION=develop SELION_GRID_VERSION=1.1.0-SNAPSHOT REPO=snapshots SELENIUM_VERSION=2.53 SELENIUM_FIX=0 make ci
after_success:
  - VERSION=develop sh -e travis-deploy-to-docker-registry.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#selion"
    on_success: always
    on_failure: always
    use_notice: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a8fc34e427360ced7ebf
    on_success: change
    on_failure: always
    on_start: never
