sudo: required
language: c
services:
  - docker
cache:
  directories:
    - $TRAVIS_BUILD_DIR/test/.m2
script:
  - docker version
  - VERSION=develop make ci
after_success:
  - VERSION=develop sh -e travis-deploy-to-docker-registry.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#selion"
    on_success: always
    on_failure: always
    use_notice: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a8fc34e427360ced7ebf
    on_success: change
    on_failure: always
    on_start: never
